fix: correctly parse auth config
Example of error:

```

 LEDGER_DB_URI=sqlite:// LEDGER_USE_HTTPS=false LEDGER_AUTH_CLIENT_CERT_ENABLED=false npm start

> five-bells-ledger@11.0.0 start /Users/alan/Projects/five-bells-ledger
> node src/app.js

/Users/alan/Projects/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:225
    throw new ServerError(
    ^

ServerError: Missing ledger_TLS_KEY or ledger_TLS_CERTIFICATE
    at validateEnvConfig (/Users/alan/Projects/five-bells-ledger/node_modules/five-bells-shared/lib/config.js:225:11)
```